services:
  db:
    container_name: avitoMerch-db
    image: postgres:17-alpine3.21 
    restart: always
    environment:
      - "POSTGRES_DB=${PG_DB}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data

  backend:
    container_name: avitoMerch-backend
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "${HTTP_PORT}:8080"
    volumes:
      - .:/app
    restart: unless-stopped

volumes:
  db_volume:

  
      