services:
  db:
    image: postgres:17-alpine3.21 
    environment:
      - "POSTGRES_DB=${PG_DB}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data
volumes:
  db_volume: